FROM python:3.11.12-slim

RUN apt-get update

RUN mkdir /simple_sdk

WORKDIR /simple_sdk

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD ["gunicorn", "src.main:app", "--workers", "1", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:8000"]